title: Ted's Tidbits
baseurl: /
url: http://tidbits.tedchoward.com

# Build Settings
markdown: kramdown
#theme:
gems:
  - jekyll-paginate
  - bourbon
  - neat
  - jekyll-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

safe: false
port: 4000
permalink: /:year/:month/:title/
paginate:  10
future: true

autoprefixer:
  browsers:
    - last 2 versions